// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using projekUas_Atun.Models;

namespace projekUas_Atun.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.13");

            modelBuilder.Entity("projekUas_Atun.Models.Db_Peminjaman", b =>
                {
                    b.Property<string>("Id_Peminjaman")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("Id_Member")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<string>("NamaMember")
                        .HasColumnType("text");

                    b.Property<string>("NamaMobil")
                        .HasColumnType("text");

                    b.Property<string>("NamaPaket")
                        .HasColumnType("text");

                    b.Property<string>("NamaSupir")
                        .HasColumnType("text");

                    b.Property<DateTime>("Tgl_Kembali")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("Tgl_Pinjam")
                        .HasColumnType("datetime");

                    b.HasKey("Id_Peminjaman");

                    b.HasIndex("Id_Member");

                    b.ToTable("Tb_Peminjaman");
                });

            modelBuilder.Entity("projekUas_Atun.Models.Member", b =>
                {
                    b.Property<string>("Id_Member")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("Alamat")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<string>("JenisKelamin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NamaMember")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id_Member");

                    b.ToTable("Tb_Member");
                });

            modelBuilder.Entity("projekUas_Atun.Models.Mobil", b =>
                {
                    b.Property<string>("Id_mobil")
                        .HasColumnType("varchar(767)");

                    b.Property<int>("Harga")
                        .HasColumnType("int");

                    b.Property<string>("ImageMobil")
                        .HasColumnType("text");

                    b.Property<string>("Merk")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NamaMobil")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id_mobil");

                    b.ToTable("Tb_Mobil");
                });

            modelBuilder.Entity("projekUas_Atun.Models.Paket", b =>
                {
                    b.Property<string>("Id_Paket")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("LamaPeminjaman")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NamaPaket")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id_Paket");

                    b.ToTable("Tb_paket");
                });

            modelBuilder.Entity("projekUas_Atun.Models.Roles", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tb_Roles");
                });

            modelBuilder.Entity("projekUas_Atun.Models.Supir", b =>
                {
                    b.Property<string>("Id_Supir")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("Alamat")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("HargaPerhari")
                        .HasColumnType("int");

                    b.Property<string>("NamaSupir")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id_Supir");

                    b.ToTable("Tb_Supir");
                });

            modelBuilder.Entity("projekUas_Atun.Models.User", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<string>("RolesId")
                        .HasColumnType("varchar(767)");

                    b.HasKey("Username");

                    b.HasIndex("RolesId");

                    b.ToTable("Tb_User");
                });

            modelBuilder.Entity("projekUas_Atun.Models.Db_Peminjaman", b =>
                {
                    b.HasOne("projekUas_Atun.Models.Member", "IdMember")
                        .WithMany()
                        .HasForeignKey("Id_Member");

                    b.Navigation("IdMember");
                });

            modelBuilder.Entity("projekUas_Atun.Models.User", b =>
                {
                    b.HasOne("projekUas_Atun.Models.Roles", "Roles")
                        .WithMany()
                        .HasForeignKey("RolesId");

                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
